services:
  rvmshopengine-api:
    build:
      context: .
      dockerfile: src/RVM.ShopEngine.API/Dockerfile
    container_name: rvmshopengine-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=rvmtech-db;Database=rvmshopengine;Username=rvmtech;Password=${POSTGRES_PASSWORD}
      - ApiKeys__Keys__0__Key=${API_KEY_0}
      - ApiKeys__Keys__0__AppId=${API_APP_ID_0}
      - ApiKeys__Keys__0__Name=${API_APP_NAME_0}
      - App__PathBase=/shopengine
      - Seq__ServerUrl=http://187.77.48.215:5341
    volumes:
      - app-data:/app/data
    networks:
      - rvmtech

volumes:
  app-data:

networks:
  rvmtech:
    external: true
